name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build and test
      run: ./mvnw clean package
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_PRIVATE_KEY }}
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Build the Docker image
      run: | 
        docker build -t robdillon/demoapp1 .
        docker tag robdillon/demoapp1 registry.digitalocean.com/robdillon-docker-springboot/robdillon/demoapp1
        docker push registry.digitalocean.com/robdillon-docker-springboot/robdillon/demoapp1